site_name: Genshin info
site_url: https://docs.genshin-info.top/
site_author: Genshin info
repo_url: https://github.com/genshin-info/docs
repo_name: genshin-info/docs
edit_uri: _edit/main/docs/ru
docs_dir: '../../docs/ru'
site_dir: '../../generated/ru'
site_description: >-
  Документация к API Genshin Info
copyright: Genshin info &copy 2022. Все права защищены.
theme:
  name: material
  custom_dir: '../../overrides/'
  logo: assets/images/logo.svg
  favicon: assets/images/purple.svg
  icon:
    repo: fontawesome/brands/git-alt
  language: ru
  font:
    text: Roboto
  palette:
    - scheme: default
      media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Включить тёмную тему
    - scheme: slate
      media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Включить светлую тему
  features:
 #   - navigation.indexes
    - navigation.top
   # - toc.integrate
    - navigation.tabs
    #- navigation.tabs.sticky
plugins:
  - search:
      lang:
        - ru
        - en
extra:
  alternate:
    - name: Русский
      link: /ru/
      lang: ru

    - name: English
      link: /en/
      lang: en
  social:
    - icon: fontawesome/brands/discord
      link: https://genshin-info.top/discord
      name: Discord
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - meta
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: '#'
      baselevel: 2
      separator: "_"
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Главная: index.md
  - API:
      - Персонажи: api/charteres.md
      - Артефакты: api/artefacts.md
      - Прочее: api/utils.md
  - Библиотеки:
      - TS (JS): lib/ts.md
  - Часто заваемые вопросы: faq.md
  - Внос вклада в проект: contributing.md
