blank_issues_enabled: false
contact_links:
  - name: Official Discord Server
    url: https://genshin-info.top/discord
    about:
      If you are experiencing issues with service, go to our support in our
      Discord server.