name: Build docs
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: install mkdocs
        run: |
          pip install mkdocs mkdocs-material mkdocs-redirects mkdocs-git-revision-date-localized-plugin
          mkdocs --version
      - name: build docs
        run: |
          mkdocs build -f config/ru/mkdocs.yml
      #    mkdocs build -f config/en/mkdocs.yml
      - name: deploy to github pages
        uses: 'JamesIves/github-pages-deploy-action@4.1.3'
        with:
          branch: gh-pages
          folder: generated
